---
- hosts: worker
  become: yes
  tasks:
    - name: package_installation_ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Execute shell script
      script: /home/ubuntu/k8-install-by-ansible/install-script.sh
